# Pre-commit hooks configuration for AnimeSorter
repos:
  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: debug-statements
      - id: check-docstring-first

  # Black (code formatting)
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--config=pyproject.toml]

  # Ruff (linting and import sorting)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter (ruff format)
      - id: ruff-format

  # MyPy (type checking) - optional, can be enabled later
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-all]
  #       args: [--config-file=pyproject.toml]

# Global settings
default_stages: [pre-commit]
fail_fast: false

# File patterns to exclude
exclude: |
  (?x)^(
      \.git/.*|
      \.venv/.*|
      venv/.*|
      build/.*|
      dist/.*|
      .*\.egg-info/.*|
      __pycache__/.*|
      .*\.pyc$|
      .*\.pyo$
  )$
