version: '3.8'

services:
  animesorter:
    build:
      context: .
      target: production
    image: animesorter:latest
    container_name: animesorter-app
    environment:
      - DISPLAY=:99
      - QT_QPA_PLATFORM=offscreen
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    networks:
      - animesorter-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import src.core.file_parser; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  animesorter-dev:
    build:
      context: .
      target: builder
    image: animesorter:dev
    container_name: animesorter-dev
    environment:
      - DISPLAY=:99
      - QT_QPA_PLATFORM=offscreen
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - animesorter-network
    command: bash
    stdin_open: true
    tty: true
    profiles: ["dev"]

  test:
    build:
      context: .
      target: builder
    image: animesorter:test
    container_name: animesorter-test
    environment:
      - DISPLAY=:99
      - QT_QPA_PLATFORM=offscreen
      - PYTHONPATH=/app
      - CI=true
    volumes:
      - .:/app:ro
      - test-reports:/app/test-reports:rw
    networks:
      - animesorter-network
    command: >
      bash -c "
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3 &&
        pytest tests/
          --cov=src
          --cov-report=xml:/app/test-reports/coverage.xml
          --cov-report=html:/app/test-reports/htmlcov
          --cov-report=term-missing
          --junitxml=/app/test-reports/junit.xml
          -v
      "
    profiles: ["test"]

volumes:
  test-reports:
    driver: local

networks:
  animesorter-network:
    driver: bridge
