"""
AnimeSorter Application Core

애플리케이션 레벨의 핵심 컴포넌트들을 제공합니다.
"""

# 백그라운드 작업 이벤트
# Core 모듈
from src.core import (AppSettings, FileManager,  # type: ignore[import-untyped]
                     FileOperationResult, FileParser, ParsedMetadata,
                     SettingsManager, TMDBAnimeInfo, TMDBClient)

# 애플리케이션 이벤트
from .application_events import (FileOperationAppliedEvent,
                                 FileOperationPlannedEvent, FilesScannedEvent,
                                 MediaFileCreatedEvent, MediaFileDeletedEvent,
                                 MediaFileMovedEvent, MediaFileRenamedEvent,
                                 MediaGroupCreatedEvent, MetadataSyncedEvent,
                                 OperationFailedEvent, OperationStatus,
                                 OperationType, ScanStatus,
                                 SettingsChangedEvent)
from .background_events import (TaskCancelledEvent, TaskCompletedEvent,
                                TaskFailedEvent, TaskPriority,
                                TaskProgressEvent, TaskQueueStatusEvent,
                                TaskRetryEvent, TaskStartedEvent, TaskStatus)
# 백그라운드 작업 클래스
from .background_task import BaseTask, TaskResult, TaskSignals
# Command 패턴
from .commands import (BaseCommand, BatchCommandCompletedEvent,
                       BatchCommandStartedEvent, BatchFileCommand,
                       CommandError, CommandExecutedEvent, CommandFailedEvent,
                       CommandInvoker, CommandRedoneEvent, CommandResult,
                       CommandStatus, CommandUndoneEvent, CopyFileCommand,
                       CreateDirectoryCommand, DeleteFileCommand, ICommand,
                       ICommandInvoker, MoveFileCommand, RenameFileCommand)
from .container import DIContainer, get_container
from .domain import (MediaFile, MediaGroup, MediaLibrary, MediaMetadata,
                     MediaQuality, MediaSource, MediaType, ProcessingFlag)
from .events import BaseEvent, TypedEventBus, get_event_bus
# 저널링 시스템
from .journal import (FileOperationDetails, IJournalEntry, IJournalManager,
                      IRollbackEngine, ITransaction, JournalCleanupEvent,
                      JournalConfiguration, JournalEntry,
                      JournalEntryCreatedEvent, JournalEntryStatus,
                      JournalEntryType, JournalEntryUpdatedEvent,
                      JournalManager, RollbackCompletedEvent, RollbackEngine,
                      RollbackResult, RollbackStartedEvent, RollbackStrategy,
                      Transaction, TransactionCommittedEvent,
                      TransactionRolledBackEvent, TransactionStartedEvent,
                      TransactionStatus)
# 미디어 데이터 이벤트
from .media_data_events import (FilterCriteria, GroupingStrategy,
                                MediaDataClearedEvent, MediaDataErrorEvent,
                                MediaDataExportCompletedEvent,
                                MediaDataExportStartedEvent, MediaDataFilter,
                                MediaDataFilteringCompletedEvent,
                                MediaDataFilteringStartedEvent,
                                MediaDataGrouping,
                                MediaDataGroupingCompletedEvent,
                                MediaDataGroupingStartedEvent,
                                MediaDataLoadStartedEvent,
                                MediaDataParsingCompletedEvent,
                                MediaDataParsingProgressEvent,
                                MediaDataReadyEvent, MediaDataStatistics,
                                MediaDataStatus, MediaDataUpdatedEvent)
# 파일 정리 이벤트
from .organization_events import (OrganizationCancelledEvent,
                                  OrganizationCompletedEvent,
                                  OrganizationErrorType,
                                  OrganizationFailedEvent,
                                  OrganizationPreflightCompletedEvent,
                                  OrganizationPreflightData,
                                  OrganizationPreflightStartedEvent,
                                  OrganizationProgressEvent,
                                  OrganizationResult, OrganizationStartedEvent,
                                  OrganizationStatus,
                                  OrganizationValidationCompletedEvent,
                                  OrganizationValidationFailedEvent,
                                  OrganizationValidationResult,
                                  OrganizationValidationStartedEvent)
# 프리플라이트 검사
from .preflight import (BasePreflightChecker, BatchPreflightCompletedEvent,
                        BatchPreflightStartedEvent, CircularReferenceChecker,
                        DiskSpaceChecker, FileConflictChecker, FileLockChecker,
                        IPreflightChecker, IPreflightCoordinator,
                        PathValidityChecker, PermissionChecker,
                        PreflightCheckFailedEvent, PreflightCheckResult,
                        PreflightCompletedEvent, PreflightCoordinator,
                        PreflightIssue, PreflightIssueFoundEvent,
                        PreflightResult, PreflightSeverity,
                        PreflightStartedEvent)
# Safety 시스템
from .safety import (BackupConfiguration, BackupInfo, BackupManager,
                     BackupStrategy, ConfirmationManager, ConfirmationRequest,
                     ConfirmationResponse, IBackupManager,
                     IConfirmationManager, IInterruptionManager,
                     InterruptionManager, InterruptionRequest,
                     InterruptionResult, ISafetyManager, SafetyConfiguration,
                     SafetyManager, SafetyMode, SafetyStatus)
# Safety System 이벤트들
from .safety_events import (BackupCleanupEvent, BackupCompletedEvent,
                            BackupFailedEvent, BackupStartedEvent,
                            BatchOperationWarningEvent,
                            ConfirmationRequiredEvent,
                            ConfirmationResponseEvent,
                            OperationInterruptedEvent,
                            OperationInterruptRequestedEvent,
                            OperationResumeRequestedEvent, SafetyAlertEvent,
                            SafetyModeChangedEvent, SafetyStatusUpdateEvent,
                            TestModeOperationEvent)
from .services import (BackgroundTaskService, FileOrganizationService,
                       FileScanService, IBackgroundTaskService,
                       IFileOrganizationService, IFileScanService,
                       IMediaDataService, ITMDBSearchService, IUIUpdateService,
                       MediaDataService, TMDBSearchService, UIUpdateService)
from .setup import cleanup_application, get_service, initialize_application
# Note: simple_events.py has been removed due to duplication with application_events.py
# All event classes are now imported from application_events.py
# TMDB 검색 이벤트
from .tmdb_search_events import (TMDBBulkSearchCompletedEvent,
                                 TMDBBulkSearchProgressEvent,
                                 TMDBBulkSearchStartedEvent,
                                 TMDBCacheUpdatedEvent,
                                 TMDBManualSelectionCompletedEvent,
                                 TMDBManualSelectionRequestedEvent, TMDBMatch,
                                 TMDBMatchConfidence, TMDBMatchFoundEvent,
                                 TMDBMatchNotFoundEvent, TMDBMediaType,
                                 TMDBRateLimitEvent, TMDBSearchCancelledEvent,
                                 TMDBSearchCompletedEvent,
                                 TMDBSearchFailedEvent,
                                 TMDBSearchProgressEvent, TMDBSearchQuery,
                                 TMDBSearchResult, TMDBSearchResultsEvent,
                                 TMDBSearchStartedEvent, TMDBSearchStatistics,
                                 TMDBSearchStatus, TMDBSearchType)
# UI 이벤트
from .ui_events import (ErrorMessageEvent, FileCountUpdateEvent,  # UI 업데이트 이벤트
                        MemoryUsageUpdateEvent, MenuStateUpdateEvent,
                        ProgressUpdateEvent, SettingsExportEvent,
                        SettingsImportEvent, SettingsResetEvent,
                        SettingsSavedEvent, StatusBarUpdateEvent,
                        SuccessMessageEvent, TableDataUpdateEvent,
                        ThemeUpdateEvent, UIStateUpdateEvent,
                        WindowTitleUpdateEvent)
# Undo/Redo 시스템
from .undo_redo import (CommandPushedToStackEvent, IUndoRedoManager,
                        QtBatchFileCommand, QtCommandWrapper,
                        QtCopyFileCommand, QtCreateDirectoryCommand,
                        QtDeleteFileCommand, QtMoveFileCommand,
                        QtRenameFileCommand, RedoExecutedEvent,
                        StackClearedEvent, UndoExecutedEvent,
                        UndoRedoConfiguration, UndoRedoEnabledEvent,
                        UndoRedoErrorEvent, UndoRedoManager,
                        UndoRedoMenuManager, UndoRedoShortcutManager,
                        UndoRedoStackChangedEvent, UndoRedoStatistics,
                        UndoRedoToolbarManager, UndoRedoUIIntegration)

__all__ = [
    "DIContainer",
    "get_container",
    "TypedEventBus",
    "BaseEvent",
    "get_event_bus",
    "MediaFile",
    "MediaGroup",
    "MediaLibrary",
    "MediaType",
    "ProcessingFlag",
    "MediaQuality",
    "MediaSource",
    "MediaMetadata",
    # Core 모듈
    "FileManager",
    "FileOperationResult",
    "FileParser",
    "ParsedMetadata",
    "SettingsManager",
    "AppSettings",
    "TMDBClient",
    "TMDBAnimeInfo",
    # 애플리케이션 이벤트
    "FilesScannedEvent",
    "MetadataSyncedEvent",
    "FileOperationPlannedEvent",
    "FileOperationAppliedEvent",
    "OperationFailedEvent",
    "MediaFileCreatedEvent",
    "MediaGroupCreatedEvent",
    "ScanStatus",
    "OperationType",
    "OperationStatus",
    # UI 이벤트
    "StatusBarUpdateEvent",
    "ProgressUpdateEvent",
    "FileCountUpdateEvent",
    "MemoryUsageUpdateEvent",
    "UIStateUpdateEvent",
    "ErrorMessageEvent",
    "SuccessMessageEvent",
    "TableDataUpdateEvent",
    "WindowTitleUpdateEvent",
    "MenuStateUpdateEvent",
    "ThemeUpdateEvent",
    "SettingsChangedEvent",
    "SettingsSavedEvent",
    "SettingsResetEvent",
    "SettingsImportEvent",
    "SettingsExportEvent",
    # 백그라운드 작업 이벤트
    "TaskStatus",
    "TaskPriority",
    "TaskStartedEvent",
    "TaskProgressEvent",
    "TaskCompletedEvent",
    "TaskFailedEvent",
    "TaskCancelledEvent",
    "TaskQueueStatusEvent",
    "TaskRetryEvent",
    # Command 패턴
    "BaseCommand",
    "CommandResult",
    "CommandStatus",
    "CommandError",
    "ICommand",
    "MoveFileCommand",
    "CopyFileCommand",
    "DeleteFileCommand",
    "RenameFileCommand",
    "CreateDirectoryCommand",
    "BatchFileCommand",
    "CommandInvoker",
    "ICommandInvoker",
    "CommandExecutedEvent",
    "CommandUndoneEvent",
    "CommandRedoneEvent",
    "CommandFailedEvent",
    "BatchCommandStartedEvent",
    "BatchCommandCompletedEvent",
    # 프리플라이트 검사
    "BasePreflightChecker",
    "PreflightResult",
    "PreflightSeverity",
    "PreflightIssue",
    "IPreflightChecker",
    "FileConflictChecker",
    "PermissionChecker",
    "DiskSpaceChecker",
    "PathValidityChecker",
    "CircularReferenceChecker",
    "FileLockChecker",
    "PreflightCoordinator",
    "IPreflightCoordinator",
    "PreflightCheckResult",
    "PreflightStartedEvent",
    "PreflightCompletedEvent",
    "PreflightIssueFoundEvent",
    "PreflightCheckFailedEvent",
    "BatchPreflightStartedEvent",
    "BatchPreflightCompletedEvent",
    # 저널링 시스템
    "JournalEntry",
    "JournalEntryType",
    "JournalEntryStatus",
    "FileOperationDetails",
    "IJournalEntry",
    "Transaction",
    "TransactionStatus",
    "ITransaction",
    "JournalManager",
    "IJournalManager",
    "JournalConfiguration",
    "RollbackEngine",
    "IRollbackEngine",
    "RollbackResult",
    "RollbackStrategy",
    "JournalEntryCreatedEvent",
    "JournalEntryUpdatedEvent",
    "TransactionStartedEvent",
    "TransactionCommittedEvent",
    "TransactionRolledBackEvent",
    "RollbackStartedEvent",
    "RollbackCompletedEvent",
    "JournalCleanupEvent",
    # Undo/Redo 시스템
    "QtCommandWrapper",
    "QtMoveFileCommand",
    "QtCopyFileCommand",
    "QtDeleteFileCommand",
    "QtRenameFileCommand",
    "QtCreateDirectoryCommand",
    "QtBatchFileCommand",
    "UndoRedoManager",
    "IUndoRedoManager",
    "UndoRedoConfiguration",
    "UndoRedoStatistics",
    "UndoExecutedEvent",
    "RedoExecutedEvent",
    "UndoRedoStackChangedEvent",
    "UndoRedoEnabledEvent",
    "CommandPushedToStackEvent",
    "StackClearedEvent",
    "UndoRedoErrorEvent",
    "UndoRedoUIIntegration",
    "UndoRedoMenuManager",
    "UndoRedoToolbarManager",
    "UndoRedoShortcutManager",
    # Safety 시스템
    "BackupManager",
    "IBackupManager",
    "BackupConfiguration",
    "BackupStrategy",
    "BackupInfo",
    "ConfirmationManager",
    "IConfirmationManager",
    "ConfirmationRequest",
    "ConfirmationResponse",
    "InterruptionManager",
    "IInterruptionManager",
    "InterruptionRequest",
    "InterruptionResult",
    "SafetyManager",
    "ISafetyManager",
    "SafetyConfiguration",
    "SafetyMode",
    "SafetyStatus",
    # Safety System 이벤트들
    "BackupStartedEvent",
    "BackupCompletedEvent",
    "BackupFailedEvent",
    "BackupCleanupEvent",
    "ConfirmationRequiredEvent",
    "ConfirmationResponseEvent",
    "BatchOperationWarningEvent",
    "OperationInterruptRequestedEvent",
    "OperationInterruptedEvent",
    "OperationResumeRequestedEvent",
    "SafetyModeChangedEvent",
    "TestModeOperationEvent",
    "SafetyStatusUpdateEvent",
    "SafetyAlertEvent",
    # 파일 정리 이벤트
    "OrganizationStatus",
    "OrganizationErrorType",
    "OrganizationValidationResult",
    "OrganizationResult",
    "OrganizationPreflightData",
    "OrganizationValidationStartedEvent",
    "OrganizationValidationCompletedEvent",
    "OrganizationValidationFailedEvent",
    "OrganizationPreflightStartedEvent",
    "OrganizationPreflightCompletedEvent",
    "OrganizationStartedEvent",
    "OrganizationProgressEvent",
    "OrganizationCompletedEvent",
    "OrganizationFailedEvent",
    "OrganizationCancelledEvent",
    # 미디어 데이터 이벤트
    "MediaDataStatus",
    "GroupingStrategy",
    "FilterCriteria",
    "MediaDataStatistics",
    "MediaDataFilter",
    "MediaDataGrouping",
    "MediaDataLoadStartedEvent",
    "MediaDataParsingProgressEvent",
    "MediaDataParsingCompletedEvent",
    "MediaDataGroupingStartedEvent",
    "MediaDataGroupingCompletedEvent",
    "MediaDataFilteringStartedEvent",
    "MediaDataFilteringCompletedEvent",
    "MediaDataReadyEvent",
    "MediaDataErrorEvent",
    "MediaDataUpdatedEvent",
    "MediaDataClearedEvent",
    "MediaDataExportStartedEvent",
    "MediaDataExportCompletedEvent",
    # TMDB 검색 이벤트
    "TMDBSearchStatus",
    "TMDBMediaType",
    "TMDBSearchType",
    "TMDBMatchConfidence",
    "TMDBSearchResult",
    "TMDBMatch",
    "TMDBSearchQuery",
    "TMDBSearchStatistics",
    "TMDBSearchStartedEvent",
    "TMDBSearchProgressEvent",
    "TMDBSearchResultsEvent",
    "TMDBMatchFoundEvent",
    "TMDBMatchNotFoundEvent",
    "TMDBSearchCompletedEvent",
    "TMDBSearchFailedEvent",
    "TMDBSearchCancelledEvent",
    "TMDBCacheUpdatedEvent",
    "TMDBRateLimitEvent",
    "TMDBManualSelectionRequestedEvent",
    "TMDBManualSelectionCompletedEvent",
    "TMDBBulkSearchStartedEvent",
    "TMDBBulkSearchProgressEvent",
    "TMDBBulkSearchCompletedEvent",
    # 백그라운드 작업 클래스
    "BaseTask",
    "TaskResult",
    "TaskSignals",
    # 서비스
    "IFileScanService",
    "FileScanService",
    "IUIUpdateService",
    "UIUpdateService",
    "IBackgroundTaskService",
    "BackgroundTaskService",
    "IFileOrganizationService",
    "FileOrganizationService",
    "IMediaDataService",
    "MediaDataService",
    "ITMDBSearchService",
    "TMDBSearchService",
    # 초기화
    "initialize_application",
    "cleanup_application",
    "get_service",
]

# 별칭 설정
FileDeletedEvent = MediaFileDeletedEvent
FileMovedEvent = MediaFileMovedEvent
FileRenamedEvent = MediaFileRenamedEvent
ISettingsManager = SettingsManager
